FORMAT: 1A
HOST: http://localhost:8090/v4

# Mastermind REST API v4
This is the API documentation for the Mastermind game by Team Alpha.

# Group Game
<!-- include(game/gameCreate.apib) -->
<!-- include(game/gameGuess.apib) -->
<!-- include(game/gameCancel.apib) -->

# Group Statistics
<!-- include(stat/statGlobal.apib) -->
<!-- include(stat/statPersonal.apib) -->