FORMAT: 1A
HOST: http://localhost:8090/v2

# Mastermind REST API v2
This is the API documentation for the Mastermind game by Team Alpha.

# Group Game
<!-- include(game/gameCreate.apib) -->
<!-- include(game/gameGuess.apib) -->
<!-- include(game/gameCancel.apib) -->